Develop
Tsung-Yen/taipei-day-trip-website pull request #6
Opened 2021-05-14 10:20 UTC by Tsung-Yen

老師好~~我是吳宗晏
以下是Week4 作業
http://3.131.86.32:3000/
http://3.131.86.32:3000/attraction/7

2021-05-14 16:40 UTC, cwpeng requested changes
我打算測試使用同一個 Email 註冊第二次的時候，你的後端程式就出現 MySQL Connection is Lost 的錯誤，你可以自己確認看看，修正後和我說 ~

2021-05-15 08:38 UTC, Tsung-Yen commented
老師我修正完成了~~~

2021-05-15 15:37 UTC, cwpeng commented
看起來沒問題了，但請重新發 Review Request 給我 ~

2021-05-15 17:06 UTC, Tsung-Yen commented
老師我發出去了

2021-05-15 18:57 UTC, cwpeng approved these changes
OK.

2021-05-16 04:55 UTC, merged